[package]
name = "mancie"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
eframe = "0.31.0"
egui_extras = { version = "0.31.0", features = ["default", "image"] }
env_logger = "0.11.6"
rfd = "0.15.2"
which = "7.0.2"
